name: luxora
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.5.4

dependencies:
   flutter:
      sdk: flutter
   iconsax: ^0.0.8
   get: ^4.6.6
   pretty_http_logger: ^1.0.4
   shared_preferences: ^2.3.5
   http: ^1.2.2
   flutter_animated_splash: ^0.0.10
   flutter_svg: ^2.0.17

dev_dependencies:
   flutter_test:
      sdk: flutter
   flutter_lints: ^4.0.0

flutter:
   uses-material-design: true
   assets:
    - assets/images/
